all: Open_File.o RASM4.o Add_String_Keyboard.o Byte_Count.o Create_List.o Delete_String.o Node_Count.o View_Strings.o Read_File.o Add_String_File.o Edit_String.o

Open_File.o :
	as -g -o ~/RASM4/build/Open_File.o Open_File.s

RASM4.o :
	as -g -o ~/RASM4/build/RASM4.o RASM4.s

Add_String_Keyboard.o :
	as -g -o ~/RASM4/build/Add_String_Keyboard.o Add_String_Keyboard.s

Byte_Count.o :
	as -g -o ~/RASM4/build/Byte_Count.o Byte_Count.s

Create_List.o :
	as -g -o ~/RASM4/build/Create_List.o Create_List.s

Delete_String.o :
	as -g -o ~/RASM4/build/Delete_String.o Delete_String.s

Node_Count.o :
	as -g -o ~/RASM4/build/Node_Count.o Node_Count.s

View_Strings.o :
	as -g -o ~/RASM4/build/View_Strings.o View_Strings.s
	
Read_File.o	:
	as -g -o ~/RASM4/build/Read_File.o Read_File.s
	
Add_String_File.o :
	as -g -o ~/RASM4/build/Add_String_File.o Add_String_File.s

Edit_String.o :
	as -g -o ~/RASM4/build/Edit_String.o Edit_String.s
