all: Open_File.o Line_Length.o RASM4.o

Open_File.o :
	as -g -o ~/RASM4/build/Open_File.o Open_File.s

Line_Length.o :
	as -g -o ~/RASM4/build/Line_Length.o Line_Length.s

RASM4.o :
	as -g -o ~/RASM4/build/RASM4.o RASM4.s
